### PR TITLE
Issue 48 - Add custom assert message

### PR DESCRIPTION
**Pull request by jonatask**
Closes issue #48

### CODE REVIEW

**Comment by puneet0191** [comment]
@jonatask  I am not sure, how this allows adding custom msg?

**Comment by jonatask** [comment]
@puneet0191 It improves the displayed message in the test report.
Beyond the mismatch percentage, now the message also says which is the baseline it compared against.

**Comment by puneet0191** [comment]
@jonatask thanks for the clarification, but issue https://github.com/codecept-js/codeceptjs-resemblehelper/issues/48 talks about custom assert message or ability to pass such message as parameter. 

Also could you please fix merge conflict so I could merge it to 1.9.1 and prepare for release

**Comment by jonatask** [comment]
@puneet0191 The conflict has been changed.

**Pull request merged**
