### PR TITLE
Update Dependecies, Fix Fatal Error with mkdirp and Mac

### PR DESCRIPTION
**Pull request by puneet0191**
Fixes: https://github.com/codecept-js/codeceptjs-resemblehelper/issues/45 
https://github.com/codecept-js/codeceptjs-resemblehelper/issues/61

### CODE REVIEW

**Comment by puneet0191** [comment]
@jonatask could you please help me test this fix, if everything works we can merge your PR's along with this one and release a new version.

**Comment by jonatask** [comment]
@puneet0191 Yes, I will test it.

**Comment by jonatask** [comment]
@puneet0191 When installing the dependency then I see these:

```
npm WARN ws@7.2.3 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.2.3 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
```

Is it normal?

**Comment by jonatask** [comment]
The functional aspects are ok. There was not impact in the directory, mismatch calculation, elements and whole page checks, neither reports, prepareBaseline, images or any functional aspect.

**Pull request merged**
